module.exports = {
	target: {
		src: [
			"src/**/*.scss",
			"!src/icons/nice-icons.tmpl.scss",
			"!src/stylesheets/vendor/**/*.scss",
			"!src/stylesheets/helpers/hacks/**/*.scss",
			"!src/stylesheets/typography/_typography-icons.scss" // Typography icons is autogenerated
		]
	},
	options: {
		configFile: "./src/stylesheets/.sass-lint.yml",
		formatter: "table"
	}
};
